# Header
menu:
  Home: /
  Archives: /archives
  Github:
    url: https://github.com/distums
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: WELCOME & HAVE FUN

# URL of the Home page image
index_cover: /img/banner.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: distums
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-88559975-1

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/distums
twitter_handle:
facebook_url:
github_url: https://github.com/distums
gitlab_url:
linkedin_url:
mailto: yiqidaoshan@gmail.com